### ISSUE TITLE
Slidinig expiration

### ISSUE THREAD

**Issue by hex22a** [crftd/post3ree-boilerplate#8]
For JWT

**Comment by hex22a** [comment]
@ykirill do you remember our algorithm? 😅

**Comment by ykirill** [comment]
@hex22a , nope oO

**Comment by hex22a** [comment]
shit

**Comment by AlbertFazullin** [comment]
here is my draft
1. Server sends access JWT and refresh token after login/password auth
2. let access token expire in 1 hour and refresh token expire in 10 days
3. we use access token to get access to the resources
4. before every request we send refresh token to the separate endpoint to get a new token pair

if access token is expired we don't grant access to the resource
if refresh token is expired we don't sent new access token

**Comment by AlbertFazullin** [comment]
well i can send a broken PR
seems like it creates infinite page loading on mac =(
maybe something wrong with middlewares

**Comment by AlbertFazullin** [comment]
fixed!
